config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'flats/:id', to: 'flats#show', as: :flat
  root to: 'flats#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
require 'open-uri'
require 'json'

class FlatsController < ApplicationController
    FLATS_URL = "https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json".freeze
    before_action :set_flats

    def index
    end

    def show
        @flat = @flats.find { |flat| flat["id"] == params[:id].to_i }
    end

    private

    def set_flats
        @flats = JSON.parse(open(FLATS_URL).read)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<h1>Nice flats to rent !</h1>
<ul>
    <% @flats.each do |flat| %>
        <li>
            <%= flat['name'] %>
            <%= link_to flat['id'], flat_path(flat['id']) %>
            <%= flat['price'] %>
            <%= flat['priceCurrency'] %>
        </li> 
    <% end %>
</ul>

app/views/flats/show.html.erb
<h1> <%=@flat['name'] %> </h1>
<h2>
    Price: <%=@flat['price']%>
    <%=@flat['priceCurrency'] %>
</h2>

<%= image_tag @flat['imageUrl'], alt: @flat['name'] %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsNoDatabaseAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>